<a href="https://colab.research.google.com/github/Rassya06/earthquakes/blob/main/earthquake_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install folium
import pandas as pd
import folium
import plotly.graph_objects as go
cities = pd.read_csv("katalog_gempa.csv")
print(cities)

Requirement already satisfied: folium in /usr/local/lib/python3.10/dist-packages (0.14.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from folium) (0.6.0)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from folium) (1.23.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from folium) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2023.7.22)
              tgl            ot   lat     lon  depth  mag  \
0      2008/11/01  21:02:43.058 -9.18  119.06     10  4.9
1      2008/11/01  20:58:50.248 -6.55  129.64     10  4.6
2      2008/11/01  17:43:12.941 -7.01  106.63    121  3.7
3      2008/11/01  16:24:14.755 -3.30  127.85     10  3.2
4      2008/11/01  16:20:37.327 -6.41  129.54     70  4.3
...           ...           ...   ...     ...    ...  ...
92882  2023/01/26  02:25:09.288  3.24  127.18     10  4.0
92883  2023/01/26  02:15:03.893  2.70  127.10     10  3.9
92884  2023/01/26  01:57:08.885 -7.83  121.07     10  3.8
92885  2023/01/26  01:46:21.009  3.00  127.16     10  4.1
92886  2023/01/26  00:00:35.181 -8.87  118.95     10  2.4

                           remark  strike1  dip1  rake1  strike2  dip2  rake2
0        Sumba Region - Indonesia      NaN   NaN    NaN      NaN   NaN    NaN
1                       Banda Sea      NaN   NaN    NaN      NaN   NaN    NaN
2                Java - Indonesia      NaN   NaN    NaN      NaN   NaN    NaN
3               Seram - Indonesia      NaN   NaN    NaN      NaN   NaN    NaN
4                       Banda Sea      NaN   NaN    NaN      NaN   NaN    NaN
...                           ...      ...   ...    ...      ...   ...    ...
92882  Talaud Islands - Indonesia      NaN   NaN    NaN      NaN   NaN    NaN
92883        Northern Molucca Sea      NaN   NaN    NaN      NaN   NaN    NaN
92884                  Flores Sea      NaN   NaN    NaN      NaN   NaN    NaN
92885        Northern Molucca Sea      NaN   NaN    NaN      NaN   NaN    NaN
92886  Sumbawa Region - Indonesia      NaN   NaN    NaN      NaN   NaN    NaN

[92887 rows x 13 columns]

In [ ]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92887 entries, 0 to 92886
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   tgl      92887 non-null  object
 1   ot       92887 non-null  object
 2   lat      92887 non-null  float64
 3   lon      92887 non-null  float64
 4   depth    92887 non-null  int64
 5   mag      92887 non-null  float64
 6   remark   92887 non-null  object
 7   strike1  2735 non-null   float64
 8   dip1     2735 non-null   float64
 9   rake1    2735 non-null   float64
 10  strike2  2735 non-null   float64
 11  dip2     2735 non-null   float64
 12  rake2    2735 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 9.2+ MB

In [ ]:
cities=cities.drop(['strike1','dip1','rake1','strike2','dip2','rake2'],axis=1)
cities

,tgl,ot,lat,lon,depth,mag,remark
0,2008/11/01,21:02:43.058,-9.18,119.06,10,4.9,Sumba Region - Indonesia
1,2008/11/01,20:58:50.248,-6.55,129.64,10,4.6,Banda Sea
2,2008/11/01,17:43:12.941,-7.01,106.63,121,3.7,Java - Indonesia
3,2008/11/01,16:24:14.755,-3.30,127.85,10,3.2,Seram - Indonesia
4,2008/11/01,16:20:37.327,-6.41,129.54,70,4.3,Banda Sea
...,...,...,...,...,...,...,...
92882,2023/01/26,02:25:09.288,3.24,127.18,10,4.0,Talaud Islands - Indonesia
92883,2023/01/26,02:15:03.893,2.70,127.10,10,3.9,Northern Molucca Sea
92884,2023/01/26,01:57:08.885,-7.83,121.07,10,3.8,Flores Sea
92885,2023/01/26,01:46:21.009,3.00,127.16,10,4.1,Northern Molucca Sea
92886,2023/01/26,00:00:35.181,-8.87,118.95,10,2.4,Sumbawa Region - Indonesia

In [ ]:
strong_quake=cities[cities['mag']>=6.1]

In [ ]:
strong_quake.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 316 entries, 70 to 92505
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tgl     316 non-null    object
 1   ot      316 non-null    object
 2   lat     316 non-null    float64
 3   lon     316 non-null    float64
 4   depth   316 non-null    int64
 5   mag     316 non-null    float64
 6   remark  316 non-null    object
dtypes: float64(3), int64(1), object(3)
memory usage: 19.8+ KB

In [ ]:
strong_quake.drop_duplicates(inplace=True)
strong_quake

<ipython-input-28-cb66da6f7877>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tgl,ot,lat,lon,depth,mag,remark
70,2008/11/07,16:04:27.451,-6.76,129.37,39,6.2,Banda Sea
143,2008/11/22,16:11:54.420,-4.17,101.43,10,6.2,Southern Sumatra - Indonesia
144,2008/11/22,16:01:00.895,-4.46,101.13,5,6.4,Southern Sumatra - Indonesia
155,2008/11/25,14:12:08.517,-3.77,113.26,10,6.4,Borneo
199,2008/12/06,10:55:26.662,-7.56,124.74,404,6.3,Banda Sea
...,...,...,...,...,...,...,...
90653,2022/12/03,09:49:42.115,-7.33,107.55,119,6.1,Java - Indonesia
92087,2023/01/09,17:47:34.171,-7.38,130.18,122,7.5,Tanimbar Islands Reg. - Indonesia
92309,2023/01/15,22:30:03.048,1.97,97.91,47,6.2,Northern Sumatra - Indonesia
92493,2023/01/18,06:06:16.115,2.82,127.04,69,7.0,Northern Molucca Sea
92504,2023/01/18,00:34:46.442,-0.02,123.27,144,6.1,Minahassa Peninsula - Sulawesi

In [ ]:
strong_quake.duplicated()

70       False
143      False
144      False
155      False
199      False
         ...
90653    False
92087    False
92309    False
92493    False
92504    False
Length: 202, dtype: bool

In [ ]:
strong_quake.isna().any()

tgl       False
ot        False
lat       False
lon       False
depth     False
mag       False
remark    False
dtype: bool

In [ ]:
print(strong_quake.remark.unique())

['Banda Sea' 'Southern Sumatra - Indonesia' 'Borneo' 'Celebes Sea'
 'South China Sea' 'Talaud Islands - Indonesia' 'Mindanao - Philippines'
 'Irian Jaya Region - Indonesia' 'Northern Molucca Sea'
 'Philippine Islands Region' 'Sumbawa Region - Indonesia'
 'Malay Peninsula' 'Sulawesi - Indonesia' 'Halmahera - Indonesia'
 'Irian Jaya - Indonesia' 'Sunda Strait - Indonesia'
 'South of Sumbawa - Indonesia' 'South of Java - Indonesia'
 'Southern Molucca Sea' 'Northern Sumatra - Indonesia'
 'New Guinea - Papua New Guinea' 'Bali Sea' 'Ceram Sea'
 'Southwest of Sumatra - Indonesia' 'South of Bali - Indonesia'
 'Minahassa Peninsula - Sulawesi' 'Arafura Sea' 'Java Sea'
 'Java - Indonesia' 'Flores Sea' 'Timor Region' 'Sumba Region - Indonesia'
 'Seram - Indonesia' 'Off West Coast of Northern Sumatra'
 'North of Halmahera - Indonesia' 'Tanimbar Islands Reg. - Indonesia']

In [ ]:
import numpy as np
earthquake = strong_quake.copy()
earthquake['category'] = np.select(
    [(earthquake['mag'].between(6.0,7.9,inclusive='right')),
     (earthquake['mag'].between(7.9,8,inclusive='right')),
     (earthquake['mag']>8)],
    ['Strong', 'Major','Great'],
    default='Undetermined'
)
earthquake

,tgl,ot,lat,lon,depth,mag,remark,category
70,2008/11/07,16:04:27.451,-6.76,129.37,39,6.2,Banda Sea,Strong
143,2008/11/22,16:11:54.420,-4.17,101.43,10,6.2,Southern Sumatra - Indonesia,Strong
144,2008/11/22,16:01:00.895,-4.46,101.13,5,6.4,Southern Sumatra - Indonesia,Strong
155,2008/11/25,14:12:08.517,-3.77,113.26,10,6.4,Borneo,Strong
199,2008/12/06,10:55:26.662,-7.56,124.74,404,6.3,Banda Sea,Strong
...,...,...,...,...,...,...,...,...
90653,2022/12/03,09:49:42.115,-7.33,107.55,119,6.1,Java - Indonesia,Strong
92087,2023/01/09,17:47:34.171,-7.38,130.18,122,7.5,Tanimbar Islands Reg. - Indonesia,Strong
92309,2023/01/15,22:30:03.048,1.97,97.91,47,6.2,Northern Sumatra - Indonesia,Strong
92493,2023/01/18,06:06:16.115,2.82,127.04,69,7.0,Northern Molucca Sea,Strong
92504,2023/01/18,00:34:46.442,-0.02,123.27,144,6.1,Minahassa Peninsula - Sulawesi,Strong

In [ ]:
#map of major earthquakes
fig = go.Figure(data=go.Scattergeo(
    lat=strong_quake.lat,
    lon=strong_quake.lon,
    text=strong_quake.remark,
    marker=dict(
        color=strong_quake.mag,
        colorscale='burg',
        opacity=1,
        size=strong_quake['mag']**1.3,
        colorbar=dict(
            titleside="right",
            outlinecolor="rgba(0,68,128,255)",
            ticks="outside",
            showticksuffix="last"
        )
    )
))
fig.update_layout(
    geo = dict(
        scope = 'asia',
        showland = True,
        subunitcolor = "rgb(255, 128, 255)",
        countrycolor = 'grey',
        showsubunits = True,
        showcountries = True,
        resolution = 50,
        lonaxis = dict(
            showgrid = True,
            gridwidth = 0.5,
            range= [ 94.0, 142.0 ],
            dtick = 5
        ),
        lataxis = dict (
            showgrid = True,
            gridwidth = 0.5,
            range= [ -6.0, 11.0 ],
            dtick = 5
        )
    ),
    title='Map of major earthquakes in Indonesia',
)
fig.show()